package view

import (
	"gioui.org/widget"
	"golang.org/x/exp/shiny/materialdesign/icons"
)

var actionDoneIcon, _ = widget.NewIcon(icons.ActionDone)
var actionDoneAllIcon, _ = widget.NewIcon(icons.ActionDoneAll)
var alertErrorIcon, _ = widget.NewIcon(icons.AlertErrorOutline)
var submitIcon, _ = widget.NewIcon(icons.ContentSend)
var expandIcon, _ = widget.NewIcon(icons.NavigationUnfoldMore)
var collapseIcon, _ = widget.NewIcon(icons.NavigationUnfoldLess)
var voiceMessageIcon, _ = widget.NewIcon(icons.AVMic)
var audioCallIcon, _ = widget.NewIcon(icons.CommunicationPhone)
var videoCallIcon, _ = widget.NewIcon(icons.AVVideoCall)
var micOffIcon, _ = widget.NewIcon(icons.AVMicOff)
var settingsIcon, _ = widget.NewIcon(icons.ActionSettings)
var photoLibraryIcon, _ = widget.NewIcon(icons.ImagePhotoLibrary)
var imageBrokenIcon, _ = widget.NewIcon(icons.ImageBrokenImage)
var refreshIcon, _ = widget.NewIcon(icons.NavigationRefresh)
var syncIcon, _ = widget.NewIcon(icons.NotificationSync)
var contentCutIcon, _ = widget.NewIcon(icons.ContentContentCut)
var contentCopyIcon, _ = widget.NewIcon(icons.ContentContentCopy)
var contentPasteIcon, _ = widget.NewIcon(icons.ContentContentPaste)
var downloadIcon, _ = widget.NewIcon(icons.FileFileDownload)
var cloudDownloadIcon, _ = widget.NewIcon(icons.FileCloudDownload)
var playIcon, _ = widget.NewIcon(icons.AVPlayArrow)
var pauseIcon, _ = widget.NewIcon(icons.AVPause)
var chatIcon, _ = widget.NewIcon(icons.CommunicationChatBubble)
var filesIcon, _ = widget.NewIcon(icons.FileFolder)
var folderOpenIcon, _ = widget.NewIcon(icons.FileFolderOpen)
var gifIcon, _ = widget.NewIcon(icons.ActionGIF)
var imageIcon, _ = widget.NewIcon(icons.ImageImage)
var unknownIcon, _ = widget.NewIcon(icons.FileAttachment)
var bookIcon, _ = widget.NewIcon(icons.ActionBook)
var musicIcon, _ = widget.NewIcon(icons.ImageMusicNote)
var videoIcon, _ = widget.NewIcon(icons.AVPlayCircleFilled)
