// generated by go run gen.go; DO NOT EDIT

package icons

var list = []struct {
	name string
	data []byte
}{
	{"Apk", Apk},
	{"Audio", Audio},
	{"Browse", Browse},
	{"FileExport", FileExport},
	{"Video", Video},
}
