package icons

import (
	"gioui.org/widget"
	"golang.org/x/exp/shiny/materialdesign/icons"
)

var ActionDoneIcon, _ = widget.NewIcon(icons.ActionDone)
var ActionDoneAllIcon, _ = widget.NewIcon(icons.ActionDoneAll)
var AlertErrorIcon, _ = widget.NewIcon(icons.AlertErrorOutline)
var SubmitIcon, _ = widget.NewIcon(icons.ContentSend)
var ExpandIcon, _ = widget.NewIcon(icons.NavigationUnfoldMore)
var CollapseIcon, _ = widget.NewIcon(icons.NavigationUnfoldLess)
var VoiceMessageIcon, _ = widget.NewIcon(icons.AVMic)
var AudioCallIcon, _ = widget.NewIcon(icons.CommunicationPhone)
var VideoCallIcon, _ = widget.NewIcon(icons.AVVideoCall)
var MicOffIcon, _ = widget.NewIcon(icons.AVMicOff)
var SettingsIcon, _ = widget.NewIcon(icons.ActionSettings)
var PhotoLibraryIcon, _ = widget.NewIcon(icons.ImagePhotoLibrary)
var ImageBrokenIcon, _ = widget.NewIcon(icons.ImageBrokenImage)
var RefreshIcon, _ = widget.NewIcon(icons.NavigationRefresh)
var SyncIcon, _ = widget.NewIcon(icons.NotificationSync)
var ContentCutIcon, _ = widget.NewIcon(icons.ContentContentCut)
var ContentCopyIcon, _ = widget.NewIcon(icons.ContentContentCopy)
var ContentPasteIcon, _ = widget.NewIcon(icons.ContentContentPaste)
var DownloadIcon, _ = widget.NewIcon(icons.FileFileDownload)
var CloudDownloadIcon, _ = widget.NewIcon(icons.FileCloudDownload)
var AddIcon, _ = widget.NewIcon(icons.ContentAdd)
var PlayIcon, _ = widget.NewIcon(icons.AVPlayArrow)
var PauseIcon, _ = widget.NewIcon(icons.AVPause)
var ChatIcon, _ = widget.NewIcon(icons.CommunicationChatBubble)
var FilesIcon, _ = widget.NewIcon(icons.FileFolder)
var BrowseIcon, _ = widget.NewIcon(Browse)
var ImageIcon, _ = widget.NewIcon(icons.ImageImage)
var UnknownIcon, _ = widget.NewIcon(icons.FileAttachment)
var BookIcon, _ = widget.NewIcon(icons.ActionBook)
var MusicIcon, _ = widget.NewIcon(Audio)
var VideoIcon, _ = widget.NewIcon(Video)
var ApkIcon, _ = widget.NewIcon(Apk)
var FileExportIcon, _ = widget.NewIcon(FileExport)
